
services:
  agenday:    
    image: clean-start
    expose:
      - 3000
    restart: always
    container_name: clean-start
    env_file:
      - .env
    networks:
      service_network:

networks:
  service_network:
    external: 
      name: nginx-letsencrypt_service_network
